import LayoutProvider from "@/components/Layout/LayoutProvider";
import { Poppins } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import Providers from "./providers";


const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

export const metadata = {
  title: "TPNL | University Portal",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${poppins.className} flex min-h-screen flex-col `}
      >
        <Providers>
          <LayoutProvider>{children}</LayoutProvider>
          <Toaster position="top-center" richColors />
        </Providers>
      </body>
    </html>
  );
}
